name: ci
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          python-version: "3.11"
      - run: uv pip install -e .[dev]
      - run: uv run pytest -q
      - run: uv run specguard-chem run --suite basic --protocol L1 --model heuristic --limit 5
